### ISSUE TITLE
Improve the UI of Navbar

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/ChatSociety#2]

**Comment by zainbinfurqan** [comment]
Can I contribute ?

**Comment by swapnilsparsh** [comment]
> Can I contribute ?

Sure

**Comment by Atharv777** [comment]
what design do you want?

**Comment by zainbinfurqan** [comment]
you can assign it to other since i am little bit confused about design

**Comment by swapnilsparsh** [comment]
> what design do you want?

Something better than the current Navbar.
You can add a hover effect or something else.

**Comment by dontech09** [comment]
Can I Contributete

**Comment by swapnilsparsh** [comment]
> Can I Contribute

Best of Luck 😀

**Comment by swapnilsparsh** [comment]
Issue resolved by @dontech09 #10
