### ISSUE TITLE
Add a Pre Loader

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/ChatSociety#7]

**Comment by GeorgeET15** [comment]
Hi sir,

I would like to contribute can you assign me

**Comment by Neel-Shah224** [comment]
Hello,
I would love to contribute to this issue.

And I have also found few preloader for this
1.) [https://codepen.io/kathykato/pen/YzKGrqd](https://codepen.io/kathykato/pen/YzKGrqd)
2.) [https://codepen.io/mr_alien/pen/FDLjg/](https://codepen.io/mr_alien/pen/FDLjg/)
3.) [https://codepen.io/jh3y/pen/VwLdVoZ](https://codepen.io/jh3y/pen/VwLdVoZ)
Do tell which one to use or is there any need to find another preloader
Thanks in Advance

**Comment by swapnilsparsh** [comment]
> Hello, I would love to contribute to this issue.
> 
> And I have also found few preloader for this 1.) https://codepen.io/kathykato/pen/YzKGrqd 2.) https://codepen.io/mr_alien/pen/FDLjg/ 3.) https://codepen.io/jh3y/pen/VwLdVoZ Do tell which one to use or is there any need to find another preloader Thanks in Advance

All the designs are awesome.
2 one is looking great.

**Comment by swapnilsparsh** [comment]
Issue resolved by @Neel-Shah224 #12
